version: '3'

services:
  db_luuminet:
      container_name: db_luuminet
      image: mysql
      command: [ "--log_bin_trust_function_creators=1", "--default-authentication-plugin=mysql_native_password"]
      restart: always
      environment:
        MYSQL_DATABASE: db_luuminet
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        log_bin_trust_function_creators: 1
      volumes:
        - mysql_user:/var/lib/mysql
      ports:
        - "3306:3306"
  
  adminer:
    container_name: adminerLumminet
    image: adminer
    restart: always
    ports:
      - "8089:8080"

volumes:
  mysql_user:
  mysql: